export const message = {
    managedByagent: "Managed By Agent",
    addAgent: "Add Managing Agent",
    nameCompany: "Name of the company",
    namePerson: "Name of contact Person",
    mobileNo: "Mobile Number",
    lanlineNo: "Lanline Number",
    licenceNo: "License Number",
    primaryEmail: "Primary Email",
    SecondaryEmail: "Secondary Email",
    Submit: "Submit",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete Agent",
    deleteManging: "Delete Managing agent",
    areyousure: "Are you sure you want to delete managing agent details?",

    warn_email: "Invalid email",
    warn_mobile: "Invalid mobile number",
    warn_lanline: "Invalid lanline number",
    warn_lincense: "Invalid lincense number",

    required_email: "Email is required",
    required_company: "Company's name is required",
    required_person: "Person's name is required",
    required_mobile: "Mobile number is required",
    required_lanline: "Lanline number is required",
    required_licence: "License number is required",
}

